### ISSUE TITLE
recapcha code

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-nation-adjusting#10]
same deal. work your magic holmes.

Paste this snippet before the closing </head> tag on your HTML template:
````
<script src='https://www.google.com/recaptcha/api.js'></script>
````
Paste this snippet at the end of the ````<form>```` where you want the reCAPTCHA widget to appear:
````
<div class="g-recaptcha" data-sitekey="6LeOwgoTAAAAAOQV7KIG4tPqWB4sQS3pQWU6fz0d"></div>
````

due:
8-3-15      11p

**Comment by AaronAguilar** [comment]
Done. 9127450a6728ba6d7ff86e122f4947a5b2d6185b

**Comment by rodneystrong** [comment]
lookin goood lookin good!
