### ISSUE TITLE
Logo adjustment

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-nation-adjusting#11]
spoke with client today, he likes the bottom 3 logos (ones with the globe and yellow underline)

he would like to see a version with the "N" in Nation and "A" in Adjusting capitalized and the rest of the letters in lowercase. 

please make a new logo sheet with ALL versions of the logo done this way EXCEPT the one with the house on it.

Here's a link to the file in drive for quick reference: https://drive.google.com/file/d/0BwNEeMVrMpDLRFZFaTRjNmI3QjA/view?usp=sharing

due:
8-6-15   10p

**Comment by AaronAguilar** [comment]
I'm going to have to swap the font for it. The font being used Bebas Neue only writes in CAPS.

**Comment by AaronAguilar** [comment]
Done. https://drive.google.com/open?id=0BwNEeMVrMpDLbGwwQUtqVUhxMnc

**Comment by rodneystrong** [comment]
Thanks for getting this done!

Unfortunately it's not complete. 

Please re-read the instructions above and include the missing logos.

**Comment by AaronAguilar** [comment]
Apologies, I forgot to include the untouched version of the House Logo. 

New link : https://drive.google.com/open?id=0BwNEeMVrMpDLOVo1MzlDQ3BYNEk

**Comment by rodneystrong** [comment]
Sorry, but this is still wrong.. 

Please, please, re-read the instructions from the first comment on this issue and include the missing logos.

If you're still unsure, please approach me or slack me.

**Comment by AaronAguilar** [comment]
New link: https://drive.google.com/open?id=0BwNEeMVrMpDLV0RMODdTYVFGaUk

**Comment by rodneystrong** [comment]
Sorry Aaron, but you included the logo with the house again. 

Please remove the logo with the house in it.

**Comment by AaronAguilar** [comment]
Apologies! This time for sure :
https://drive.google.com/open?id=0BwNEeMVrMpDLeGxYVVFwZVBMaHc
