### ISSUE TITLE
Fix the "r"  (screenshot)

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-nation-adjusting#6]
![fix](https://cloud.githubusercontent.com/assets/539962/8755064/fc987376-2c7c-11e5-96ae-638cb5fd43af.JPG)

There is a rogue "r" in that code. Find it and remove and update gh-pages please

due date:
7-17-15 4p

**Comment by purplyrocky** [comment]
done
31acf8a73d6ed720a9432ff5937a91b553c72f63
