### ISSUE TITLE
replace logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-nation-adjusting#7]
![logo](https://cloud.githubusercontent.com/assets/539962/8944462/ad86cf28-3535-11e5-9778-00e8bdba6119.jpg)

Replace it with the same version but make sure the extra white space is cropped out. 

due date:
7-28-15  5p

**Comment by AaronAguilar** [comment]
Changed it to a PNG image. http://editllc.github.io/client-nation-adjusting/

**Comment by rodneystrong** [comment]
good move sir. thanks again!
